# Generated by Django 4.2 on 2025-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(default="select", max_length=255),
            preserve_default=False,
        ),
    ]
