# Generated by Django 4.2 on 2025-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_alter_question_options_question_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
